---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - attribution.krato.io
  resources:
  - resourceattributions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - attribution.krato.io
  resources:
  - resourceattributions/finalizers
  verbs:
  - update
- apiGroups:
  - attribution.krato.io
  resources:
  - resourceattributions/status
  verbs:
  - get
  - patch
  - update
